#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: matrixconduit/matrix-conduit
  # -- image tag
  tag: v0.4.0
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below and commented variables in values.yaml
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Set the Server Name
  CONDUIT_SERVER_NAME: 'your.server.name'
  # -- Set the Database Backend
  CONDUIT_DATABASE_BACKEND: 'rocksdb'
  # -- Flag to allow registration
  CONDUIT_ALLOW_REGISTRATION: true
  # -- Flag to allow federation
  CONDUIT_ALLOW_FEDERATION: true
  # -- Set the maximum request size
  CONDUIT_MAX_REQUEST_SIZE: '20000000'
  # -- Set a list of trusted servers
  CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
  # -- Set the maximum concurrent requests
  CONDUIT_MAX_CONCURRENT_REQUESTS: '100'
  # -- Set conduit log configuration
  CONDUIT_LOG: 'info,rocket=off,_=off,sled=off'

service:
  main:
    primary: true
    ports:
      http:
        port: 6167

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml for full listing
persistence:
  # -- Conduit config database storage
  config:
    # -- If config storage should be enabled
    enabled: true
    mountPath: /var/lib/matrix-conduit
    accessMode: ReadWriteOnce
