on: pull_request
name: "Delete Branches After Merge"
jobs:
  branchCleanup:
    name: "Delete Branch"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: branch cleanup
      uses: jessfraz/branch-cleanup-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
